//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COVIDMARK_MARKET_OTOMASYONU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class covidmarkEntities5 : DbContext
    {
        public covidmarkEntities5()
            : base("name=covidmarkEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adre> adres { get; set; }
        public virtual DbSet<firma> firmas { get; set; }
        public virtual DbSet<hareket> harekets { get; set; }
        public virtual DbSet<kategori> kategoris { get; set; }
        public virtual DbSet<personel> personels { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<urun> uruns { get; set; }
        public virtual DbSet<urunAli> urunAlis { get; set; }
        public virtual DbSet<urunSati> urunSatis { get; set; }
    }
}
