//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COVIDMARK_MARKET_OTOMASYONU
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel()
        {
            this.urunAlis = new HashSet<urunAlis>();
            this.urunSatis = new HashSet<urunSatis>();
        }
    
        public string personelNo { get; set; }
        public string personelAd { get; set; }
        public string personelSoyAd { get; set; }
        public string personelTC { get; set; }
        public string personelSifre { get; set; }
        public string personel_telefon { get; set; }
        public string personelCinsiyet { get; set; }
        public string personelGorev { get; set; }
        public int personel_adresID { get; set; }
        public string personel_adresBilgi { get; set; }
    
        public virtual adres adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urunAlis> urunAlis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urunSatis> urunSatis { get; set; }
    }
}
