//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COVIDMARK_MARKET_OTOMASYONU
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunSatis
    {
        public int satisID { get; set; }
        public int satis_islemNo { get; set; }
        public string satis_personelNo { get; set; }
        public string satis_urunBarkod { get; set; }
        public string satis_urunKod { get; set; }
        public string satisBirim { get; set; }
        public byte satisAdet { get; set; }
        public decimal satisBirimFiyat { get; set; }
        public string satisTuru { get; set; }
        public decimal satisTopTutar { get; set; }
        public System.DateTime satisTarih { get; set; }
        public Nullable<int> faturaId { get; set; }
    
        public virtual fatura fatura { get; set; }
        public virtual personel personel { get; set; }
        public virtual urun urun { get; set; }
    }
}
