//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COVIDMARK_MARKET_OTOMASYONU
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urun()
        {
            this.urunAlis = new HashSet<urunAlis>();
            this.urunSatis = new HashSet<urunSatis>();
        }
    
        public int urunID { get; set; }
        public string urunBarkod { get; set; }
        public string urunKod { get; set; }
        public string urunAd { get; set; }
        public int urun_altkatID { get; set; }
        public string urunBirim { get; set; }
        public short urunStok { get; set; }
        public decimal urunFiyat { get; set; }
        public string urunOzellik { get; set; }
    
        public virtual altKategori altKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urunAlis> urunAlis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urunSatis> urunSatis { get; set; }
    }
}
