//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COVIDMARK_MARKET_OTOMASYONU
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunAlis
    {
        public int alisID { get; set; }
        public int alis_islemNo { get; set; }
        public string alis_firmaVergiNo { get; set; }
        public string alis_personelNo { get; set; }
        public string alis_urunBarkod { get; set; }
        public string alis_urunKod { get; set; }
        public string alisBirim { get; set; }
        public byte alisAdet { get; set; }
        public decimal alisBirimFiyat { get; set; }
        public decimal alisTopTutar { get; set; }
        public System.DateTime alisTarih { get; set; }
        public Nullable<int> faturaId { get; set; }
    
        public virtual fatura fatura { get; set; }
        public virtual firma firma { get; set; }
        public virtual personel personel { get; set; }
        public virtual urun urun { get; set; }
    }
}
